# early stopping
es_monitor: v_loss_G_MSE
es_patience: 30

# checkpoint
save_top_k: 2
monitor: v_loss_G_MSE
save_last: True

# Trainer
devices: 2
epoch: 1000
fast_dev_run: False
log_every_n_step: 5
precision: 16