_target_: src.models.pl_model.SimpleFCAttention

# params of model class __init__ function
csv_out_dir: ${path.csv_out_dir}
lr: 0.0003
deepspeech_model_path: ${path.deepspeech}
fc1_dim: 1024
fc2_dim: 1024
num_classes: 16
attention_window: 8
save_name: ${name}