# @package _global_

defaults:
  - _self_
  - datamodule: new.yaml
  - model: S2BModel.yaml
  - path: cricket.yaml
  - trainer: default.yaml

name: 'first_try'
seed: 1234

resume: False
debug: False

# wandb setting
project: 'mediazen'
entity: 'normalkim'