_target_: src.datasets.new_datamodule.GGongGGongDataModule

base_dir: ${path.base_dir}
batch_size: 32
num_workers: 16
seed: ${seed}
blendshape_columns: [
  'JawForward',
  'JawOpen',
  'MouthClose',
  'MouthFunnel',
  'MouthPucker',
  'MouthDimpleLeft',
  'MouthDimpleRight',
  'MouthStretchLeft',
  'MouthStretchRight',
  'MouthRollLower',
  'MouthRollUpper',
  'MouthShrugLower',
  'MouthShrugUpper',
  'MouthPressLeft',
  'MouthPressRight',
  'CheekPuff'
]
speakers: [
  'AanSeoHue', # C
  'AnnSeoHue', # C
  'LeeYooHonew', # A
  'LeeYuJin', # B
  'Ohongsuck', # C
  'SeoHeeJoo', # C
  'Suljuhwan', # B
  'bbs', # B 
  'hbinew', # C 
  'hynew', # A
  'jiha', # A
  'kmg', # B
  'kye', # B
  'lcy', # C
  'mjki', # A
  'ohongsuck' # C
]