_target_: src.datasets.new_datamodule.TestGGongGGongDataModule

base_dir: ${path.base_dir}
batch_size: 7
num_workers: 16
seed: ${seed}
blendshape_columns: [
  'JawForward',
  'JawOpen',
  'MouthClose',
  'MouthFunnel',
  'MouthPucker',
  'MouthDimpleLeft',
  'MouthDimpleRight',
  'MouthStretchLeft',
  'MouthStretchRight',
  'MouthRollLower',
  'MouthRollUpper',
  'MouthShrugLower',
  'MouthShrugUpper',
  'MouthPressLeft',
  'MouthPressRight',
  'CheekPuff'
]